### ISSUE TITLE
separate async/sync part in "modules"/subprojects. 

### ISSUE THREAD

**Issue by mpenet** [lerouxrgd/clj-lettuce#1]
I am tempted to use this lib but we use mostly core.async in our projects. I could just bite the bullet and build utils to convert the manifold bits to c.async equivalents but it feels a bit dirty/wasteful. Would you consider shipping the manifold dependent code separately?

That would mean have an artifact for celtuce (basically everything not async, and building blocks for the rest), another for celtuce-manifold and I would gladly provide celtuce-core-async (I do something similar in my own projects https://github.com/mpenet/alia/tree/master/modules).

Thanks for the lib! Cheers

**Comment by lerouxrgd** [comment]
Sounds like a good idea, I prefer to decouple manifold/c.async/reactive impl from the core too.
I'll look more in details into alia and how to decouple async logic in a similar way for celtuce.
I'll keep you updated, thanks!

**Comment by mpenet** [comment]
Great! I ll keep an eye on the update. as I said I'd gladly work on the core.async part when it settles down. There's also an opportunity to provide wrappers for the streaming parts of lettuce via core.async and manifold after a potential spit.

**Comment by lerouxrgd** [comment]
I released 0.2.0 with celtuce split into modules (like alia).
Let me know if this works for you.

**Comment by mpenet** [comment]
Great! I ll give it a try these next few days. Thanks
