### ISSUE TITLE
Function for creating scripts has a typo: scirpt-load

### ISSUE THREAD

**Issue by viniciusd** [lerouxrgd/clj-lettuce#14]
Function for creating scripts has a typo, it is named scirpt-load, while it should be script-load.
 Any specific reason on that or is it really a typo?

**Comment by lerouxrgd** [comment]
It was a typo indeed. Thank you for noticing it, it has been fixed in `0.3.2`.

**Comment by viniciusd** [comment]
That's perfect, thanks! Just checked your commit, you have also upgraded Lettuce's version, that's awesome! I was about to create another issue for that
