### ISSUE TITLE
evalsha on cluster mode fails

### ISSUE THREAD

**Issue by viniciusd** [lerouxrgd/clj-lettuce#15]
As I want to run Lua scripts, I loaded the following script into a Redis cluster: `script load "return 2"`, in order to test celtuce's script interface.
For evaluating the respective SHA (7f923f79fe76194c868d7e1d0820de36700eb649), I am running:
```clj
(require '[celtuce.connector :as conn])
(require '[celtuce.commands :as redis])
(def connector (conn/redis-cluster "redis://SOME_REDIS_CLUSTER"))
(def cmds (conn/commands-sync connector))

(redis/evalsha cmds "7f923f79fe76194c868d7e1d0820de36700eb649" :integer "testing")

(conn/shutdown connector)
```
Which fails with the message `'CROSSSLOT Keys in request don't hash to the same slot`. _Please note I ran it against a Redis server as well, and it works fine_
In order to be sure that's not Lettuce's problem, I ran the following Java code (against the same Lettuce version), which I considered equivalent:
```java
import io.lettuce.core.cluster.RedisClusterClient;
import io.lettuce.core.cluster.api.StatefulRedisClusterConnection;
import io.lettuce.core.ScriptOutputType;
import io.lettuce.core.api.sync.RedisScriptingCommands;


public class RedisTesting {
  public static void main(String[] args) {
    RedisClusterClient client = RedisClusterClient.create("redis://SOME_REDIS_CLUSTER");
    StatefulRedisClusterConnection<String, String> connection = client.connect();
    RedisScriptingCommands sync = connection.sync();
    Object value = sync.evalsha("7f923f79fe76194c868d7e1d0820de36700eb649",
                                 ScriptOutputType.INTEGER);

    System.out.println(value);

    connection.close();
    client.shutdown();
  }
}
```
Which works just fine. I am not sure whether this is a problem related to the cluster setup or the evalsha function. Based on the error message, though, it seems more of a cluster related issue.

In order to make sure it wasn't because this script has no keys (btw, celttuce doesn't accept 0 keys), I also tried `script load "return KEYS[1]"`. Same result.
I am running that against a Redis 5.0.3 cluster on AWS.

**Comment by lerouxrgd** [comment]
I tried like this:

```clj
(redis/evalsha cmds "7f923f79fe76194c868d7e1d0820de36700eb649" :integer [])
```

And it seems fine on my end (it returns 2).
Let me know how it goes for you.

**Comment by viniciusd** [comment]
It works fine, thanks! Not sure why the former works for the single server Redis though

**Comment by viniciusd** [comment]
Now I will probably open an issue for script-load:

```clj
user=> (redis/script-load cmds "return 2")
RedisCommandExecutionException ERR Error compiling script (new function): user_script:1: '=' expected   io.lettuce.core.ExceptionFactory.createExecutionException (ExceptionFactory.java:135)
```
Which works fine from the Java side:
```java
    String value = sync.scriptLoad("return 2");

    System.out.println(value);
```

**Comment by lerouxrgd** [comment]
As mentioned in `README.md` serialization defaults to `nippy` codec, which is a good default for Clojure data structures, but it is not Lettuce's default one.

Therefore if you want to manipulate "native" Redis String you should use a different codec:

```clj
(def connector (conn/redis-cluster "redis://localhost:30001" :codec (celtuce.codec/utf8-string-codec)))
```
And then it should work.
Again let me know whether it works for you too.

**Comment by viniciusd** [comment]
That works as well. Thank you very much! And congrats for the awesome work you've done on this lib.
I'm going to re-read the README.md thorough and better understand what you pointed out.

**Comment by viniciusd** [comment]
That works. Thank you very much and congratulations for the awesome work on this lib!
Gonna re-read it all through and try to completely understand all you have pointed out.

**Comment by viniciusd** [comment]
That works. Thank you very much and congratulations for the awesome work on this lib!
Gonna re-read it all through and try to completely understand all you have pointed out
