### ISSUE TITLE
Using `defrecord` and `defprotocol` got compiling error: java.lang.IllegalArgumentException.

### ISSUE THREAD

**Issue by cmal** [lerouxrgd/clj-lettuce#16]
redis.clj:
```
(ns proj.redis
  (:require
   [celtuce.connector :as conn]
   [taoensso.timbre :as log]
   [mount.core :as mount]
   [proj.global :as g]))

(mount/defstate redis-client
  :start (let [port (get-in @g/config [:port :redis])
               connector (conn/redis-server (str "redis://localhost:" port))]
           (log/info (str "redis connection established on port: " port "."))
           connector)
  :stop (do
          (conn/shutdown redis-client)
          (log/info "redis connection closed.")))

(def cmds
  (conn/commands-sync redis-client))
```

$ lein uberjar

> java.lang.IllegalArgumentException: No implementation of method: :commands-sync of protocol: #'celtuce.connector/RedisConnector found for class: mount.core.DerefableState, compiling:(redis.clj:24:3)
> Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :commands-sync of protocol: #'celtuce.connector/RedisConnector found for class: mount.core.DerefableState, compiling:(redis.clj:24:3)

It seems syntax checking not passed when compiling.

![image](https://user-images.githubusercontent.com/1773318/65417076-d630e780-de2b-11e9-939c-582b9246ca8f.png)

![image](https://user-images.githubusercontent.com/1773318/65129716-7783fc00-da2e-11e9-9d4f-32f2eda70233.png)

I also found `redis-client` is a `celtuce.connector.RedisServer`, and `(def cmds (conn/commands-sync redis-client))` can be run in repl, but cannot be compiled.

**Comment by lerouxrgd** [comment]
Both REPL and `lein uberjar` work for me with the following code:

```clj
(ns coco.core
  (:require
   [celtuce.connector :as conn]
   [mount.core :as mount]))

(mount/defstate redis-client
  :start (conn/redis-server "redis://localhost:6379")
  :stop (conn/shutdown redis-client))

;; This is important !!! Otherwise it will not work.
(mount/start)

(def cmds
  (conn/commands-sync redis-client))
```

Moreover if I don't use `(mount/start)` and poke at `redis-client` I have this:
```clj
coco.core> (type redis-client)
mount.core.DerefableState
```

But if I use `(mount/start)` then I have the correct:
```clj
coco.core> (type redis-client)
celtuce.connector.RedisServer
```

One other thing you can do is wrap `cmds` with a `defstate` and make it depends on `redis-client` state, like this:

```clj
(mount/defstate cmds :start (conn/commands-sync redis-client))
```

**Comment by lerouxrgd** [comment]
Closing this as it is more related to `mount` usage than `celtuce`.
