### ISSUE TITLE
implementation of sscan command seems to have a mistake, not passing down the scan arguments to java class

### ISSUE THREAD

**Issue by florin-va-oltean** [lerouxrgd/clj-lettuce#18]
Hi, 

When using scan arguments (celtuce.commands/scan-args :limit 1 :match "whatever*") with function **sscan** , the scan arguments are not passed down to java class implementing sscan. 

In the namespace "celtuce.impl.server":

```clojure
 (sscan 
      ([this k]
        (.sscan this k))
      ([this k ^ScanCursor c]
        (.sscan this k c))
      ([this k ^ScanCursor c args]
        (.sscan this k c)))
```

This definition should be changed to something like:
```clojure
 (sscan 
      ([this k]
        (.sscan this k))
      ([this k ^ScanCursor c]
        (.sscan this k c))
      ([this k ^ScanCursor c ^ScanArgs args]
        (.sscan this k c args)))
```

**Comment by lerouxrgd** [comment]
Hi, Thank you for reporting this!
It has been fixed in version `0.3.3`.
