### ISSUE TITLE
Shared client resources

### ISSUE THREAD

**Issue by florin-va-oltean** [lerouxrgd/clj-lettuce#22]
I am creating several Redis connections to different servers from the same application; currently, each connection creates a set of NIO threads. It is possible in Java Lettuce to use the concept of shared resources via class `io.lettuce.core.resource.ClientResource` and share the same NIO infrastructure for all connections. 

However, this is not implemented in **celtuce** , as the methods `redis-server` or `redis-cluster` does not allow to pass the shared resource. 

I would like to make a pull request on this topic, but I would like first to confirm if indeed there is no way to use shared resources without a change in code; can you confirm?

**Comment by lerouxrgd** [comment]
Indeed it is not possible to use `ClientResource` for now. Sure, your PR is welcome !

**Comment by lerouxrgd** [comment]
Thanks for your PR GH-23, I merged it and released version `v0.3.6`.

Note that I moved `create-client-resource` and `destroy-client-resource` to the connector namespace.
